name: Tests

on: [push, pull_request]

jobs:
  run:
    strategy:
      matrix:
        go:
          - 1.16
          - 1.17
          - 1.18
        platform:
          - ubuntu-latest

      max-parallel: 3

    name: run tests
    runs-on: ${{ matrix.platform }}

    steps:
      - name: set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: checkout the code
        uses: actions/checkout@v2

      - name: install dependencies
        run: go get -v -t -d ./...

      - name: wait one minute to avoid rate limiting
        run: sleep 1m

      - name: run tests
        run: go test -v ./...
        env:
          CHECK_ID: ${{ secrets.HC_CHECK_ID }}
